### PR TITLE
adds point in polygon functionality

### PR DESCRIPTION
**Pull request by Binabh**
I am new to rust language so please let me know if any improvements need to be done. 
I will update the docs also once the implementation is approved and is good for merge.

### CODE REVIEW

**Comment by srishanbhattarai** [comment]
Thanks for sending this in. I haven't looked at this project for a while, could you provide a concrete example that benefits from this change?

**Comment by srishanbhattarai** [comment]
Thanks for sending this in. I haven't looked at this project for a while, so I'm deliberating if I am able to take on the maintenance duties of this code. Could you provide a concrete example / problem that benefits from this change?

**Comment by Binabh** [comment]
This is rust implementation of [this article](https://www.geeksforgeeks.org/how-to-check-if-a-given-point-lies-inside-a-polygon). 
It determines if the point is inside the polygon where polygon is an array of points where each point represents vertex of that polygon. 

I also have included a test to test weather denver or chicago lies in colorado using the real world coordinates.

Regarding a concrete example if we want to determine if a point `a` lies inside the polygon with vertex `[b,c,d,e]` then this method can help.

```
fn test_is_contained_in() {
        let colorado = [
            &Location(40.996549, -109.001960),
            &Location(40.983031, -102.125103),
            &Location(37.061297, -102.107194),
            &Location(37.075586, -109.001960),
        ];
        let colorado_corner = Location(37.075586, -109.001960);
        let denver = Location(39.725186, -104.984211);
        let chicago = Location(41.839142, -87.702715);
        assert_eq!(denver.is_contained_in(&colorado), true);
        assert_eq!(chicago.is_contained_in(&colorado), false);
        assert_eq!(colorado_corner.is_contained_in(&colorado), true);
    }
```
Here first condition is true because the point lies inside the polygon enclosed by points in colorado array.
Here first condition is false because the point lies outside the polygon enclosed by points in colorado array.
Here first condition is false because the point lies inside (exactly at vertex) the polygon enclosed by points in colorado array.

Let me know if this was useful and if any further explanation/changes are required.

**Comment by srishanbhattarai** [comment]
Let's take a step back and re-examine what's going on here. The linked article makes calculations assuming a 2D plane. Geospatial coordinates (lat, long) are not cartesian (x, y) coordinates - they are two different systems and therefore the math doesn't apply the same way.

The line segment between two unique cartesian coordinates is a perfectly straight line, but for geospatial coordinates, it's not necessarily true - it may outline a spherical arc instead of a straight line. It is not safe to assume that the points of a polygon outline a bounding box with straight edges when it comes to geospatial coordinates. If the polygon is created with a very large number of points then I would expect this effect to be nullified to a degree, and make it seem like test cases pass.

From what it looks like, the article you linked uses a Ray Casting odd-even algorithm, but at the very least the algorithm must be modified to use geospatial coordinates (e.g. using great circle intersections instead of 'normal' intersections). I'm not sure if I can take up the maintenance overhead of this even if the implementation was sound.

**Comment by Binabh** [comment]
Yes, you are correct there is difference between Geodetic and Cartesian coordinates. I will do the research again and be more sure about the implementation.
I am from Geomatics Engineering background and have used such Geo-spatial libraries(mostly in python). I will try to look into the  implementation there to be more sure.

Till then lets keep this PR on hold.

About maintenance part I am willing to provide maintenance support as much as I can.

**Comment by srishanbhattarai** [comment]
Given that I'm unfortunately not able to actively allocate time to this project, I think the best choice here is to not add this at the moment. 

The current implementation is broken, and in my estimation it'll be non-trivial to get it correct, even with your background. Thanks!

**Comment by srishanbhattarai** [comment]
Given that I'm unfortunately not able to actively allocate time to this project, I think the best choice here is to not add this at the moment.

The current implementation is broken, and in my estimation it'll be non-trivial to get it correct, even with your background and help.

Thanks!

**Comment by Binabh** [comment]
Sure, understandable!

**Pull request closed without merging**
