### PR TITLE
Allow to construct constant Locations

### PR DESCRIPTION
**Pull request by mlafeldt**

### CODE REVIEW

**Comment by mlafeldt** [comment]
Hey @srishanbhattarai, mind taking a look? 🙏

**Comment by srishanbhattarai** [comment]
Thanks for sending this in. I haven't looked at this project for a while, could you provide a concrete example that benefits from this change? Bit unsure about the `pub` fields for long term API stability

**Comment by mlafeldt** [comment]
Sure. One example is this code: https://github.com/mlafeldt/aws-region-nearby/pull/6/files#diff-5e2e69ad103f6876150023c4b80faa31f426770b2689746dafd7643ea6a80113R159

Here, I could turn `location()` into a const function. Also, I could share city locations between `AwsRegion` and `DenoRegion` through constants.

**Comment by mlafeldt** [comment]
If you're concerned about API stability, we might also consider adding a `new_const` function (or similar) that takes two f64's and returns a const.

**Comment by srishanbhattarai** [comment]
Thanks for the example!

> If you're concerned about API stability, we might also consider adding a new_const function (or similar) that takes two f64's and returns a const.

I think this is reasonable solution and I'd be happy to check this in.

**Comment by mlafeldt** [comment]
@srishanbhattarai PTAL :)

**Comment by srishanbhattarai** [comment]
Thanks, LGTM

**Comment by mlafeldt** [comment]
Thanks for merging. Mind cutting a new release too, so that I can use it? 🙏

**Comment by srishanbhattarai** [comment]
Released - https://crates.io/crates/geoutils/0.5.1

Sorry about the delay. Thanks again!

**Pull request merged**
